// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU-wfBCKf7U-KMWGPlvycNfcjqA_YtTCQ',
    appId: '1:197497570606:android:56c08b529ce4332e2826bf',
    messagingSenderId: '197497570606',
    projectId: 'chat-project-a27dd',
    storageBucket: 'chat-project-a27dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQViMV_b_nD0vUWH-nqwbXzy5gRPQziFc',
    appId: '1:197497570606:ios:a254741ce48547f42826bf',
    messagingSenderId: '197497570606',
    projectId: 'chat-project-a27dd',
    storageBucket: 'chat-project-a27dd.firebasestorage.app',
    iosBundleId: 'com.example.chatDasturi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp1aeWZYzQ86i22dmXf21GbjzL8gnSLWc',
    appId: '1:197497570606:web:793096216f724c2c2826bf',
    messagingSenderId: '197497570606',
    projectId: 'chat-project-a27dd',
    authDomain: 'chat-project-a27dd.firebaseapp.com',
    storageBucket: 'chat-project-a27dd.firebasestorage.app',
    measurementId: 'G-YG9MF7Q52N',
  );

}